---
- name: Configure | NGINX.
  block:
    - name: Configure | NGINX app.conf file.
      ansible.builtin.template:
        src: '{{ nginx_sites_available_app_conf_template }}'
        dest: '{{ nginx_sites_available_app_conf_path }}'
        owner: root
        group: root
        mode: 0644

    - name: Configure | NGINX link.
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      loop:
        - { src: "{{ nginx_sites_available_app_conf_path }}", dest: "{{ nginx_sites_enabled_app_conf_path }}" }
      notify: [ "Test nginx and restart" ]        
  tags: [ "role::nginx:configure_nginx_app" ]
