# Standards: 0.11
---

# 1.7.1.3 Ensure remote login warning banner is configured properly

- name: 1.7.1.3 - Ensure remote login warning banner is configured properly
  copy: >
    src=issue_net
    dest=/etc/issue.net
    owner=root
    group=root
    mode=0644

  tags:
    - level-1
    - 1.7.1.3
    - not-scored
