# Standards: 0.11
---

# 5.3.2 Ensure lockout for failed password attempts is configured

  - name: 5.3.2 Configure /etc/pam.d/password-auth
    copy: 
      src: password-auth
      dest: /etc/pam.d/password-auth
      owner: root
      group: root
      mode: 0644
    tags:
    - level-1
    - section-5
    - "5.3.2"
    - scored