# Standards: 0.11
---

# 5.3.3 Ensure password reuse is limited
 
  - name: 5.3.3 Configure /etc/pam.d/system-auth
    copy: 
      src: password-auth
      dest: /etc/pam.d/system-auth
      owner: root
      group: root
      mode: 0644
    tags:
    - level-1
    - section-5
    - "5.3.3"
    - scored
