---
- name: Configure | NGINX.
  block:
    - name:  Configure | NGINX Default conf.
      ansible.builtin.copy:
        src: "{{ nginx_sites_available_default_file }}"
        dest: '{{ nginx_sites_available_path }}'
        owner: root
        group: root
        mode: 0644

    - name:  Configure | NGINX formats conf file.
      ansible.builtin.template:
        src: '{{ nginx_logs_formats_template }}'
        dest: '{{ nginx_logs_formats_path }}'
        owner: root
        group: root
        mode: 0644

    - name:  Configure | NGINX custom configuration.
      ansible.builtin.template:
        src: '{{ nginx_locations_custom_template }}'
        dest: '{{ nginx_locations_custom_path }}'
        owner: root
        group: root
        mode: 0644

    - name: Configure | NGINX app.conf file.
      ansible.builtin.template:
        src: '{{ nginx_sites_available_app_conf_template }}'
        dest: '{{ nginx_sites_available_app_conf_path }}'
        owner: root
        group: root
        mode: 0644
  notify: [ 'Test nginx and reload' ]
  tags: [ "role::nginx:configure_nginx_app" ]
