---
- name: Install | Nodejs.
  block:
    - name: Get | Nodejs.
      ansible.builtin.shell: "{{ item }}"
      changed_when: true
      with_items:
        - "curl -sL https://rpm.nodesource.com/setup_14.x | bash"
        - "yum install -y nodejs"