---
- name: Enable | Amazon Linux extras.
  block:
    - name: Enable | EPEL repository.
      ansible.builtin.command: amazon-linux-extras enable epel
      changed_when: true

    - name: Clean | Metadata.
      ansible.builtin.command: "yum clean all -y"
      changed_when: true

    - name: Update | Packages.
      ansible.builtin.yum:
        name: "*"
        update_only: true

    - name: Install | Amazon linux extras.
      ansible.builtin.package:
        name: "{{ amazon_linux_extras['epel'] }}"
        state: present
  when: (tools.extras | default({}, false))
  tags: [ "role::extras:epel" ]
