---
- name: Import | Global handlers.
  ansible.builtin.import_role:
    name: global_handlers

- name: Enable | Amazon Linux extras.
  ansible.builtin.include_tasks: configure_amazon_linux_extras.yml

- name: Install | Packages.
  ansible.builtin.include_tasks: install_packages.yml

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
