---
- name: Install | Dnsmasq.
  block:
    - name: Download | Dnsmasq.
      ansible.builtin.copy:
        src: "{{ dnsmasq_src_dir }}"
        dest: "{{ opt_dir }}"
        owner: root
        group: root
        mode: 0755
        remote_src: false

    - name: Execute | Dnsmasq script.
      ansible.builtin.command: sh AutomateDnsmasq.sh
      changed_when: true
      args:
        chdir: "{{ opt_dir }}"

    - name: Find | Dnsmasq script.
      ansible.builtin.find:
        path: "{{ opt_dir }}"
        recurse: false
        patterns: "AutomateDnsmasq.sh"
      register: opt_dir_result

    - name: Delete | Dnsmasq script.
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items:
        - "{{ opt_dir_result.files }}"
  when: (tools.dnsmasq | default({}, false))
  tags: [ "role::extras:dnsmasq" ]
