---
- name: Congigure | WKHTMLTOX.
  block:
    - name: Download | WKHTMLTOX.
      ansible.builtin.copy:
        src: "{{ wkhtmltox_src_dir }}"
        dest: "{{ opt_dir }}"
        owner: root
        group: root
        mode: 0755
        remote_src: false

    - name: Install | WKHTMLTOX.
      ansible.builtin.package:
        name: /opt/wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm
        state: present

    - name: Configure | WKHTMLTOIMAGE link.
      ansible.builtin.file:
        src: /usr/local/bin/wkhtmltoimage
        dest: /usr/bin/wkhtmltoimage
        state: link

    - name: Configure | WKHTMLTOPDF link.
      ansible.builtin.file:
        src: /usr/local/bin/wkhtmltopdf
        dest: /usr/bin/wkhtmltopdf
        state: link

    - name: Delete | WKHTMLTOX RPM package.
      ansible.builtin.file:
        state: absent
        path: /opt/wkhtmltox-0.12.6-1.amazonlinux2.x86_64.rpm
  when: (tools.wkhtmltox | default({}, false))
  tags: [ "role::extras:wkhtmltox" ]
