---
- name: Install | Packages.
  block:
    - name: Install | Packages.
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ package_list['basic'] }}"
  when: (tools.packages | default({}, false))
