---
- name: Converge
  hosts: all
  # gather_facts: false
  # become: true
  vars:
    tools:
      extras: true
      packages: true
  tasks:
    - name: Import | CIS Role.
      ansible.builtin.import_role:
        name: cis

    - name: Import | Extras role.
      ansible.builtin.import_role:
        name: extras

    - name: Import | NGINX Role.
      ansible.builtin.import_role:
        name: nginx
      vars:
        target: "golden_image"
