---
- name: Configure Golden Server.
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars:
    tools:
      extras: true
      packages: true  
  tasks:
    - name: Import | Global handlers
      ansible.builtin.import_role:
        name: global_handlers

    # Anisible CIS role based on the CIS Amazon Linux 2 Benchmark v2.0.0"
    # Source: https://www.cisecurity.org/cis-benchmarks/
    - name: Import | CIS Role.
      ansible.builtin.import_role:
        name: cis

    - name: Import | Nginx role.
      ansible.builtin.import_role:
        name: nginx
      vars:
        target: "golden_image"
