---
- name: Configure Web Server.
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Import | Global Handlers Role.
      ansible.builtin.import_role:
        name: global_handlers

    - name: Import | NGINX Role.
      ansible.builtin.import_role:
        name: nginx

