---
- name: Configure Web Server.
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars:
    tools:
      extras: true
      packages: true
      timezone: true
      bbr: true

  tasks:
    - name: Import | Global handlers
      ansible.builtin.import_role:
        name: global_handlers

    - name: Import | Extras role.
      ansible.builtin.import_role:
        name: extras

    - name: Import | Nginx role.
      ansible.builtin.import_role:
        name: nginx
