---
- name: Configure Web Server.
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Configure | EC2 variables.
      ansible.builtin.include_tasks: prerequisites/get_ec2_facts.yml

    - name: Include | Files in vars
      ansible.builtin.include_vars:
        dir: ../vars/{{ ec2_tag_env }}/{{ ec2_tag_project }}-{{ ec2_tag_application }}

    - name: Import | Global handlers
      ansible.builtin.import_role:
        name: global_handlers

    - name: Import | NGINX Role.
      ansible.builtin.import_role:
        name: nginx
      vars:
        target: "golden_image"


- name: Configure Web Server.
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  tasks:
    - name: Configure | EC2 variables.
      ansible.builtin.include_tasks: prerequisites/get_ec2_facts.yml

    - name: Include | Files in vars
      ansible.builtin.include_vars:
        dir: ../vars/{{ ec2_tag_env }}/{{ ec2_tag_project }}-{{ ec2_tag_application }}

    - name: Import | Global handlers
      ansible.builtin.import_role:
        name: global_handlers

    - name: Import | NGINX Role.
      ansible.builtin.import_role:
        name: nginx
